### ISSUE TITLE
Support querying multiple collections at once

### ISSUE THREAD

**Issue by thunderbug1** [crate-workbench/langchain#9]
### Feature request

So, my idea would be to extend the CrateDBVectorSearch a tiny bit to not only accept a single collection_name but also a list of collection_names. This would still be compatible with the langchain sdk but also allow us to query multiple indices at once.
I think in the vectorstore implementation this should be a small change.

### Motivation

This feature is necessary when you  want to give users conditional access to different collections. This is important for business applications where not every users should have access to every collection

### Your contribution

I can help to test the feature

**Comment by amotl** [comment]
Dear Alex,

thank you for writing in. We recognize you are interested in improving the read path, when querying, i.e. when invoking any of the `similarity_search()` methods?

The specific query implementation for CrateDB is located here.

https://github.com/crate-workbench/langchain/blob/93e897051e991f09f3497e31134fd1c13801fce1/libs/langchain/langchain/vectorstores/cratedb/base.py#L235-L296

At this very spot, we would probably need to restructure the code to allow for querying multiple collections instead of just a single one, which is currently determined by `self.collection_name`.

https://github.com/crate-workbench/langchain/blob/93e897051e991f09f3497e31134fd1c13801fce1/libs/langchain/langchain/vectorstores/cratedb/base.py#L248

I am not sure the current interface should be changed.

https://github.com/crate-workbench/langchain/blob/93e897051e991f09f3497e31134fd1c13801fce1/libs/langchain/langchain/vectorstores/cratedb/base.py#L63-L75

On the other hand, this is nothing to worry about, because it does make sense to add a different method for that purpose, seperately from the current interface, if you don't have any objections about that approach.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

there is a patch now which makes an attempt to improve the situation.

- GH-15

With kind regards,
Andreas.

**Comment by thunderbug1** [comment]
I just integrated this, works well as far as I have tested it.
